### ISSUE TITLE
version regex

### ISSUE THREAD

**Issue by clatko** [Banno/asdf-kubectl#1]
This should probably be brought up in the main asdf community, but a semver regex should be applied for installation. With kubectl plugin I can do asdf install kubectl 1.8, then it becomes pretty difficult to purge my machine of this faulty version number.

**Comment by jthegedus** [comment]
This is related to https://github.com/asdf-vm/asdf/issues/216

**Comment by DustinChaloupka** [comment]
This should already be handled by the default `latest` command provided by `asdf`.

**Comment by jthegedus** [comment]
@DustinChaloupka `asdf latest` essentially runs `tail` on the `list-all` result.

https://github.com/asdf-vm/asdf/issues/763 tracks work to make `asdf latest` defer to the plugin so more complex situations can be supported. If the upstream changes from semver to `v`-prefixed semver or vice versa, then the core isn't going to know which is the latest without knowledge of the upstream, hence, the plugin author is best to make these decisions and the 763 will accomodate this workflow for proper ordering.

**Comment by DustinChaloupka** [comment]
This plugin sorts the versions which are semver formatted and do not have a `v` prefix, so the fallback mechanism from the implementation of asdf-vm/asdf#736 would still allow this plugin to correctly give the latest version. Am I missing something?

**Comment by jthegedus** [comment]
@DustinChaloupka Indeed you are correct. Sorry, I may have replied to the wrong issue.

**Comment by DustinChaloupka** [comment]
No worries!
