### ISSUE TITLE
Integration with Krew Plugins

### ISSUE THREAD

**Issue by josephlim75** [Banno/asdf-kubectl#24]
As we starting to install `krew` and `kubectl` using asdf, immediately we have noticed that plugins that was installed using `krew` is no where to be executed via `kubectl <plugin>` if our `PATH` is not pointing to the correct target path that contain the krew plugins, technically we can't execute it.  We can manually set the `PATH` but it will be an issue if we switch `krew` version, then the path has to be changed every time we make changes on `krew`.  Can we add `exec-env` to check if `krew` is installed, get the current running krew version in asdf and set it in to the `PATH` before running `kubectl`.  That will work to load plugins installed by `krew`.  Any suggestion is welcome

**Comment by josephlim75** [comment]
I actually tried to set `PATH` in `exec-env` but it still couldn't work.  If i set it in my current shell, it works.  This is what I try in `exec-env`

```
export PATH=$(dirname $(asdf which krew))/bin:$PATH
echo $PATH
```

Not sure if i should post this issue in asdf `Krew` or `Kubectl`

**Comment by DustinChaloupka** [comment]
This sounds like it should be a Krew asdf issue personally, otherwise we are going to include a weird circular dependency when `kubectl` does not need Krew to run at all.

**Comment by sbor23** [comment]
FYI the author of the asdf-krew plugin suggests that `asdf reshim` is needed after installing a plugin. This fixes the problem for me, although it's still a workaround...
https://github.com/jimmidyson/asdf-krew/issues/3

**Comment by DustinChaloupka** [comment]
It sounds like that is the intended design of `krew`, or at least would still be something to discuss there instead of with this plugin. Going to go ahead and close this.
