### ISSUE TITLE
latest-stable does not apply filters

### ISSUE THREAD

**Issue by sosheskaz** [Banno/asdf-kubectl#27]
`asdf latest kubectl` should display the latest of the given version. For example:

```bash
$ asdf latest terraform 0.14
0.14.11
```

----

Currently:

```bash
$ asdf latest kubectl 1.21
1.23.4
```

should be:

```
$ asdf latest kubectl 1.21
1.21.10
```

**Comment by sosheskaz** [comment]
This was introduced in https://github.com/asdf-community/asdf-kubectl/pull/26

**Comment by allen-servedio** [comment]
@sosheskaz - should be fixed by https://github.com/asdf-community/asdf-kubectl/pull/29
