### ISSUE TITLE
Unable to download binaries for arm64 (Apple M1)

### ISSUE THREAD

**Issue by dan-autonomic** [Banno/asdf-kubectl#33]
Looks like binaries are not being downloadable right now ?
![image](https://user-images.githubusercontent.com/97542085/213315859-340652f9-c378-428d-86c6-7efa9f44f47b.png)

**Comment by DustinChaloupka** [comment]
It worked for me for that version:
```
➜  ~ asdf install kubectl 1.19.15
Downloading kubectl from https://dl.k8s.io/release/v1.19.15/bin/darwin/amd64/kubectl
➜  ~ echo $?
0
```

**Comment by dan-autonomic** [comment]
That is right. It works for amd64 Intel architecture, but not for arm64 M1+ architecture. 
I wonder. Has it ever been available ?

**Comment by DustinChaloupka** [comment]
Oh, tiny text, didn't see the difference. https://github.com/asdf-community/asdf-kubectl#architecture-override will help you.

**Comment by dan-autonomic** [comment]
ha, that is fine. downloading a previous version with amd64 works. I just didn't expect the amd64 binaries to work, but it does. Thanks.
