### ISSUE TITLE
Rename OAUTH_TOKEN

### ISSUE THREAD

**Issue by daenney** [Banno/asdf-kubectl#4]
list-all checks for an environment variable named `OAUTH_TOKEN` to use when doing requests to the Github API. However, al ot of things use OAuth and it's possible that people already have an `OAUTH_TOKEN` environment variable completely unrelated to Github.

It would be nice if it could check for an environment variable like `GITHUB_OAUTH_TOKEN` instead, and/or if that's not found fall back to `OAUTH_TOKEN` to not break any existing uses.

**Comment by daenney** [comment]
It could also fallback/piggyback on `HOMEBREW_GITHUB_API_TOKEN` for example, to snatch that one up for Mac users.

**Comment by adamdecaf** [comment]
What about `ASDF_GITHUB_TOKEN` ? Folks might have a reason for separate tokens.

**Comment by DustinChaloupka** [comment]
https://github.com/Banno/asdf-kubectl/commit/49e924a4b8e86b57fbd2c102557fff6efae7d76b
