### ISSUE TITLE
Support multiple architectures

### ISSUE THREAD

**Issue by rynr** [Banno/asdf-kubectl#6]
When using this plugin on a raspberry pi, you get this error:
```
/home/pi/.asdf/lib/commands/shim-exec.sh: line 26: /home/pi/.asdf/installs/kubectl/1.14.1/bin/kubectl: cannot execute binary file: Exec format error
/home/pi/.asdf/lib/commands/shim-exec.sh: line 26: /home/pi/.asdf/installs/kubectl/1.14.1/bin/kubectl: Success
```
This is due to the architecture of a Raspberry Pi, it would need the `arm` version instead of the `amd64` version. The download is derived via [install](https://github.com/Banno/asdf-kubectl/blob/f5a77f3cc6a254762c75bc98fbdfcadebdbad0dc/bin/install#L33), the path contains `…/amd64/…` but would need to be `…/arm/…` for Raspberry Pi.  
Unfortunately, using `arch` to get the architecture would return `armv7l` on my machine instead of just `arm`. Perhaps someone else has an idea on how to get (or map) the different architectures. Then it'd be a simple additional variable like `platform` to enrich the URL.

**Comment by WarheadsSE** [comment]
What is needed here is to pull the architecture from `uname -m`, and then a basic mapping from there.

| CPU | value | package arch |
| --- | --- | --- |
| Intel i7 | x86_64 | amd64 |
| Exynos5422 | armv7l | arm |
| S905 | aarch64 | arm64 |

Notes:
- https://github.com/golang/go/wiki/MinimumRequirements#architectures
- For `arm`, we need to [be sure of `GOARM=X` value used to compile the binary](https://github.com/golang/go/wiki/GoArm), as `GOARM=7` will not work on an RPi which is actually `armv6l` / `GOARM=6`. A lower number can work on a higher architecture.

**Comment by DustinChaloupka** [comment]
This was added in https://github.com/Banno/asdf-kubectl/commit/1474795d1887c84c050146f367939fee6cbf3d2f, but TravisCI does not have an option to test this arch. If this is still failing after testing it out, feel free to reopen the issue.
